 1: # Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
 2: # More GitHub Actions for Azure: https://github.com/Azure/actions
 3: 
 4: name:"Build and deploy ASP app to Azure Web App - appservicetest"
 5: 
 6: "on":
 7:   push:
 8:     branches:
 9:       - main
10:   workflow_dispatch:
11: 
12: jobs:
13:   build:
14:     runs-on: windows-latest
15:     permissions:
16:       contents: read # This is required for actions/checkout
17: 
18:     steps:
19:       - uses: actions/checkout@v4
20: 
21:       - name: Setup MSBuild path
22:         uses: microsoft/setup-msbuild@v1.0.2
23: 
24:       - name: Setup NuGet
25:         uses: NuGet/setup-nuget@v1.0.5
26: 
27:       - name: Restore NuGet packages
28:         run: nuget restore project-demo.sln  # 🔧 Update this to your solution file
29: 
30:       - name: Publish to folder
31:         run: msbuild project-demo.sln  
32: 
33:       - name: Upload artifact for deployment job
34:         uses: actions/upload-artifact@v4
35:         with:
36:           name: ASP-app
37:           path: 'published/**'  # ✅ Match with previous build output
38: 
39:   deploy:
40:     runs-on: windows-latest
41:     needs: build
42:     environment:
43:       name: 'Production'
44:       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
45:     permissions:
46:       id-token: write
47:       contents: read
48: 
49:     steps:
50:       - name: Download artifact from build job
51:         uses: actions/download-artifact@v4
52:         with:
53:           name: ASP-app
54:       
55:       - name: Login to Azure
56:         uses: azure/login@v2
57:         with:
58:           client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E3BCE62D6E6F476EA88DC9443EC178B2 }}
59:           tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1E70725E081648999C115C1E3C23D0D3 }}
60:           subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E6455F345E66448BB049F22B6E4F189E }}
61: 
62:       - name: Deploy to Azure Web App
63:         id: deploy-to-webapp
64:         uses: azure/webapps-deploy@v3
65:         with:
66:           app-name: 'appservicetest'
67:           slot-name: 'Production'
68:           package: .
